---
    id: compose_better_photos_with_the_grid
    title: Compose Better Photos with the Grid
    cards:

        - 
            type: IntroCard
            exampleMediaPath: 1.jpg
            headline: Compose Better Photos with the Grid
            level: Introduction
            time: 5-10 Minutes

        - 
            type: TextCard
            text: "Thinking of a photo as a grid is the most basic concept for composition a photographer needs to understand."

        - 
            type: TextCard
            text: "Think of your photo as if it is made up of nine equal rectangles. Strong visuals use all the rectangles in the grid to tell the story."

        - 
            type: PreviewCard
            title: "Placing the grid on this photo divides one image into nine equal areas."
            medium: photo
            media: 
                - 
                    media: 3.jpg
                    media_caption: © 

        - 
            type: TextCard
            text: "Most smartphones allow you to turn this grid on in your Camera app. Use the grid when practicing these lessons."

        - 
            type: TextCard
            text: "Do not simply place your subject in the middle of the photograph with no thought to the rest of the grid."

        - 
            type: TextCard
            text: "The horizontal grid lines are sometimes called the 'eye line' or 'horizon line.' These lines are important to composing a portrait or a landscape."

        - 
            type: TextCard
            text: "If the photo is a landscape, the element that defines the horizon is often placed on either the top or bottom 'horizon line."

        - 
            type: PreviewCard
            title: "The blue line shows the horizon line in a photo of a place."
            medium: photo
            media: 
                - 
                    media: 6.jpg
                    media_caption: © 

        - 
            type: TextCard
            text: "If the photo is a portrait, the subject's eyes are often placed on either the top or bottom 'eye line.'"

        - 
            type: PreviewCard
            title: "The blue line shows the eye line in a portrait photo."
            medium: photo
            media: 
                - 
                    media: 7.jpg
                    media_caption: © 

        - 
            type: TextCard
            text: "The vertical lines and horizontal lines work together to define the frame. Place the most important elements of the composition at the the intersections of the lines. These are the points to which a viewer's eyes naturally land in a frame."

        - 
            type: PreviewCard
            title: "Note how the signs work to emphasize the grid format."
            medium: photo
            media: 
                - 
                    media: 8.jpg
                    media_caption: © 

        - 
            type: TipCard
            tags:
                - general

        - 
            type: TextCard
            text: "Fill the entire frame with compelling visual information. Use the grid to organize that information."

        - 
            type: PreviewCard
            title: "Rectangles in color show how visual information is organized on the grid."
            medium: photo
            media: 
                - 
                    media: 0.jpg
                    media_caption: 

        - 
            type: TipCard
            tags:
                - rule_of_thirds

        - 
            type: TextCard
            text: "Be careful of the edges of your frame. Try and have important shapes complete themes within the frame."

        - 
            type: PreviewCard
            title: "In this photo [subject] completes entirely within the frame."
            medium: photo
            media: 
                - 
                    media: 0.jpg
                    media_caption: © 

        - 
            type: TextCard
            text: "Next, see if you can compose better photos by thinking of the frame as a grid made up of nine rectangles."

        - 
            type: MilestoneCard
            id: milestone_start_creating
            header: Next
            text: I'm ready to try!
            icon: down
            references:
                - compose_better_photos_with_the_grid::medium_card::value

        - 
            type: PreviewCard
            title: "If possible turn on the grid feature in your mobile camera app."
            medium: photo
            media: 
                - 
                    media: rule_of_thirds_icons.png
                    media_caption: © 
            references:
                - compose_better_photos_with_the_grid::milestone_start_creating::value::true

        - 
            type: HowToCard
            text: "The card below is a clip card. Select “Capture” to launch the camera and take a photo."
            references:
                - compose_better_photos_with_the_grid::milestone_start_creating::value::true

        - 
            type: ClipCard
            medium: photo
            goals: 
                - "Fill the entire frame and use the lines and intersections in your composition."
            clipType: Action
            length: 0:20
            references:
                - compose_better_photos_with_the_grid::milestone_start_creating::value::true

        - 
            type: ReviewCard
            medium: photo
            references:
                - compose_better_photos_with_the_grid::milestone_start_creating::value::true