---
    id: introduction_to_security
    title: Introduction to Security
    classPackage: scal.io.liger.model

    cards:

        - 
            type: PreviewCard
            medium: photo
            title: INTRODUCTION TO SECURITY
            media: 
                - 
                    media: 1.png
                    media_caption: © Matt Bors 2012

        - 
            type: MarkDownCard
            body: |  
              Today, individual citizens anywhere in the world are capable of breaking stories that even 20 years ago tested the limits of professional newsrooms. Increasing connectivity afforded by smartphones and falling data costs make this possible.  
              This same connectivity creates great new risks for citizens and professional journalists alike. The standard methods of communicating online or via mobile leave a trail that is easy for skilled individuals to monitor.  

        - 
            type: MarkDownCard
            body: |  
              Journalists, activists and any people who fear they may be at risk due to their actions must use nonstandard methods of communication. These trails not only put you at risk, but may endanger your sources, contacts, and colleagues. You have a responsibility to protect not only yourself but anyone threatened by your actions.  
              The lessons that follow will first assist you to assess whether you may be under threat. After completing these lessons, you will be able to assess the risk to yourself and others. The final section will provide specific steps you can take to keep yourself safe.  
